Repository danhidsan/decide-ganimedes-almacenamiento, pull requests merged in 2018-12, with the labels that each got.

#11 chore: Incluido entorno de desarrollo con Docker
  Dockerfile
  docker-compose.yml
Labels: configuración, prioridad: alta

#14 Agregada petición API para panel de control
  decide/store/serializers.py
  decide/store/urls.py
  decide/store/views.py
Labels: mejora

#23 Almacenar varios votos
  decide/booth/templates/booth/booth.html
  decide/store/tests.py
  decide/store/views.py
  decide/voting/tests.py
Labels: prioridad: alta, repo general
